-- This module serves as the root of the `PartitionsLeanblueprint` library.
-- Import modules here that should be built as part of the library.


/- The files here are arranged approximately in order of import heirarchy -/

/- Would be nice to reorganize and rename the files at some point -/
-- import PartitionsLeanblueprint.Basic

-- import PartitionsLeanblueprint.IVT -- not used

-- import PartitionsLeanblueprint.ModularFormDefs

-- import PartitionsLeanblueprint.ModuloDefs2

-- import PartitionsLeanblueprint.BasicOperators

-- import PartitionsLeanblueprint.PowFacts

-- import PartitionsLeanblueprint.Basis

-- import PartitionsLeanblueprint.PartitionDefs

-- import PartitionsLeanblueprint.Ord

-- import PartitionsLeanblueprint.Dimension

-- import PartitionsLeanblueprint.PreliminaryResults

-- import PartitionsLeanblueprint.PrimaryLemmas

-- import PartitionsLeanblueprint.DescentArgument

-- import PartitionsLeanblueprint.FinalSection

import PartitionsLeanblueprint.RamanujanCongruence.IntegerModularForm.Defs
import PartitionsLeanblueprint.RamanujanCongruence.IntegerModularForm.ProductDefs
import PartitionsLeanblueprint.RamanujanCongruence.IntegerModularForm.Basic
import PartitionsLeanblueprint.RamanujanCongruence.IntegerModularForm.Basis
import PartitionsLeanblueprint.RamanujanCongruence.IntegerModularForm.Ord

import PartitionsLeanblueprint.RamanujanCongruence.ModularFormMod.Defs
import PartitionsLeanblueprint.RamanujanCongruence.ModularFormMod.Basic
import PartitionsLeanblueprint.RamanujanCongruence.ModularFormMod.Filtration
import PartitionsLeanblueprint.RamanujanCongruence.ModularFormMod.Operators
import PartitionsLeanblueprint.RamanujanCongruence.ModularFormMod.PowPrime
import PartitionsLeanblueprint.RamanujanCongruence.ModularFormMod.MaximalReduce

import PartitionsLeanblueprint.RamanujanCongruence.PowerSeries
import PartitionsLeanblueprint.RamanujanCongruence.EventuallyEq
import PartitionsLeanblueprint.RamanujanCongruence.Partition
import PartitionsLeanblueprint.RamanujanCongruence.FluNeZero
import PartitionsLeanblueprint.RamanujanCongruence.PreliminaryResults
import PartitionsLeanblueprint.RamanujanCongruence.PrimaryLemmas
import PartitionsLeanblueprint.RamanujanCongruence.DescentArgument
import PartitionsLeanblueprint.RamanujanCongruence.MainResult

import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.LdvdBernoulliNum
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.DeltaCarrierEq

import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.ThetaOperator.DelOperator
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.ThetaOperator.EisLPlusOne
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.ThetaOperator.KummerCongruence

import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.UOperator.HeckeOperator

import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.PIntegralModularForm.Defs
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.PIntegralModularForm.Basic
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.PIntegralModularForm.Basis
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.PIntegralModularForm.Polynomial
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.PIntegralModularForm.DelOperator
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.PIntegralModularForm.ZMod
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.Identities
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.MAlgebra
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.SquarefreeAbar
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.CoprimeAbarBbar
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.AbarSubOne
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.Theorem141
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.Filtration
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.FiltrationPow
