import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.FiltrationTheta.Foundations

open ModularFormMod

noncomputable section

namespace FiltrationTheta

/-!
## The analytic and ungraded bridges used by Proposition 1.44

The componentwise API in this project does not yet contain the ungraded
direct-sum algebra of modular forms.  The PDF uses that algebra in two places:

* the kernel of evaluation at `E₄, E₆` is the principal ideal generated by
  the Hasse relation;
* the Ramanujan differential identity produces an *integral* lift of the
  theta form in the target weight.

The definitions below state precisely those two missing interfaces.  They are
deliberately data, rather than axioms hidden inside a proof: an eventual
construction from the direct-sum algebra and q-expansions can provide an
instance, while the rest of the formalization can already be checked against
the correct statements.
-/

def HasEvaluationKernel
    {ℓ : ℕ} [isLargePrime ℓ]
    (A : HassePolynomialData (ℓ := ℓ)) : Prop :=
  ∀ (k : ZMod (ℓ - 1)) (P Q : ResidueWeightedPolynomial k),
    evalResiduePolynomial P = evalResiduePolynomial Q ↔
      P.polynomial - Q.polynomial ∈ HasseIdeal A

def HasThetaExactLift
    {ℓ : ℕ} [isLargePrime ℓ]
    {k : ZMod (ℓ - 1)} (f : ModularFormMod ℓ k) : Prop :=
  ∃ g : IntegerModularForm (f.Filtration + (ℓ + 1)),
    g.reduce ℓ = f.Theta.fourier

def HasThetaDropCriterion
    {ℓ : ℕ} [isLargePrime ℓ]
    {k : ZMod (ℓ - 1)} (f : ModularFormMod ℓ k) : Prop :=
  (∃ j' < f.Filtration + (ℓ + 1),
    f.Theta.hasWeight j') ↔
    (f.Filtration : ZMod ℓ) = 0

structure FiltrationThetaBridge (ℓ : ℕ) [isLargePrime ℓ] : Prop where
  evaluation_kernel : ∀ (A : HassePolynomialData (ℓ := ℓ)),
    HasEvaluationKernel A
  theta_exact_lift : ∀ {k : ZMod (ℓ - 1)} (f : ModularFormMod ℓ k),
    HasThetaExactLift f
  theta_drop_criterion : ∀ {k : ZMod (ℓ - 1)} (f : ModularFormMod ℓ k),
    HasThetaDropCriterion f

theorem hasEvaluationKernel
    {ℓ : ℕ} [isLargePrime ℓ] (bridge : FiltrationThetaBridge ℓ)
    (A : HassePolynomialData (ℓ := ℓ)) :
    HasEvaluationKernel A :=
  bridge.evaluation_kernel A

theorem hasThetaExactLift
    {ℓ : ℕ} [isLargePrime ℓ] (bridge : FiltrationThetaBridge ℓ)
    {k : ZMod (ℓ - 1)} (f : ModularFormMod ℓ k) :
    HasThetaExactLift f :=
  bridge.theta_exact_lift f

theorem hasThetaDropCriterion
    {ℓ : ℕ} [isLargePrime ℓ] (bridge : FiltrationThetaBridge ℓ)
    {k : ZMod (ℓ - 1)} (f : ModularFormMod ℓ k) :
    HasThetaDropCriterion f :=
  bridge.theta_drop_criterion f

end FiltrationTheta
