import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.FiltrationTheta.Bridge
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.FiltrationTheta.Statements
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.DelOperator
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.FiltrationTheta.PaperSteps

open ModularFormMod
open EisensteinSeries

noncomputable section

namespace FiltrationTheta

variable {ℓ : ℕ} [isLargePrime ℓ]
variable {k : ZMod (ℓ - 1)}

/-- The kernel of evaluation is generated by the single Hasse relation. -/
theorem residuePolynomial_eval_kernel
    (bridge : FiltrationThetaBridge ℓ)
    (A : HassePolynomialData (ℓ := ℓ))
    (k : ZMod (ℓ - 1)) (P Q : ResidueWeightedPolynomial k) :
    evalResiduePolynomial P = evalResiduePolynomial Q ↔
      P.polynomial - Q.polynomial ∈ HasseIdeal A := by
  exact hasEvaluationKernel bridge A k P Q

/-- The componentwise formalization of Theorem 1.41. -/
theorem theorem_1_41 (bridge : FiltrationThetaBridge ℓ) :
    Theorem141Statement (ℓ := ℓ) := by
  obtain ⟨A, hA_lift, hA_relation⟩ := exists_hassePolynomialData (ℓ := ℓ)
  refine ⟨A, residuePolynomial_eval_surjective A, ?_⟩
  intro k P Q
  exact residuePolynomial_eval_kernel bridge A k P Q

/-! ## Basic formal consequences of the definitions -/

theorem filtration_hasWeight (f : ModularFormMod ℓ k) :
    HasWeight f f.Filtration :=
  ModularFormMod.Filtration_spec f

/-- Multiplication by the integral lift `El` of the Hasse invariant raises an
integral weight by `ℓ - 1` without changing the reduced Fourier expansion. -/
theorem hasWeight_add_mul_pred (f : ModularFormMod ℓ k) {j : ℤ}
    (hj : HasWeight f j) (m : ℕ) :
    HasWeight f (j + (m : ℤ) * (ℓ - 1)) := by
  obtain ⟨g, hg⟩ := hj.exists_reduce
  let g' : IntegerModularForm (j + (m : ℤ) * (ℓ - 1)) :=
    (g.mul ((IntegerModularForm.El ℓ).pow m)).Icast (by
      have hℓ5 := (inferInstance : isLargePrime ℓ).AtLeastFive
      have hℓ : 1 ≤ ℓ := by omega
      rw [Nat.cast_sub hℓ]
      ring)
  refine ⟨g', ?_⟩
  rw [IntegerModularForm.reduce_Icast, IntegerModularForm.reduce_mul,
    IntegerModularForm.reduce_pow, IntegerModularForm.reduce_El]
  simpa [hg]

theorem exactFiltration_of_neZero (f : ModularFormMod ℓ k) [NeZero f] :
    HasExactFiltration f f.Filtration := by
  refine ⟨filtration_hasWeight f, ?_⟩
  intro j hj hweight
  exact (not_lt_of_ge (ModularFormMod.Filtration_le hweight)) hj

/-- The integral-weight definition of filtration is nonnegative for a nonzero
form.  This is the lower-bound fact needed when the theta form vanishes. -/
theorem filtration_nonneg (f : ModularFormMod ℓ k) [NeZero f] :
    0 ≤ f.Filtration := by
  apply le_csInf (ModularFormMod.nonempty_hasWeight_set f)
  intro j hj
  obtain ⟨g, hg⟩ := hj.exists_reduce
  by_contra! hjneg
  have g0 : g ≠ 0 := by
    intro hzero
    apply (inferInstance : NeZero f).out
    apply ModularFormMod.fourier_inj
    rw [hzero, map_zero] at hg
    simpa using hg
  exact g0 (by
    apply IntegerModularForm.carrier_inj
    ext x
    rw [ModularFormClass.levelOne_neg_weight_eq_zero hjneg]
    rfl)

theorem lowerWeight_iff_filtration_lt (f : ModularFormMod ℓ k) (j : ℤ)
    [NeZero f] :
    HasLowerWeight f j ↔ f.Filtration < j := by
  constructor
  · rintro ⟨j', hj', hweight⟩
    exact lt_of_le_of_lt (ModularFormMod.Filtration_le hweight) hj'
  · intro hj
    exact ⟨f.Filtration, hj, filtration_hasWeight f⟩

/-! These lemmas isolate the exact interfaces needed by the two theta
statements.  The first is the direct `IntegerModularForm`-lift argument; the
second is the elementary conversion from a zero residue to divisibility by
`ℓ`. -/

theorem theta_hasWeight_target_of_exact_integral_reduction
    (f : ModularFormMod ℓ k)
    (h : ∃ g : IntegerModularForm (ThetaTargetWeight f),
      g.reduce ℓ = f.Theta.fourier) :
    HasWeight f.Theta (ThetaTargetWeight f) := by
  exact DelOperator.theta_hasWeight_target_of_exact_integral_reduction f h

theorem theta_hasLowerWeight_iff_prime_divides_of_drop_criterion
    (f : ModularFormMod ℓ k)
    (hdrop : HasLowerWeight f.Theta (ThetaTargetWeight f) ↔
      (f.Filtration : ZMod ℓ) = 0) :
    HasLowerWeight f.Theta (ThetaTargetWeight f) ↔
      PrimeDividesFiltration f := by
  exact DelOperator.theta_hasLowerWeight_iff_of_drop_criterion f hdrop

/-! ## The formalized intermediate statements from the paper -/

/-- The numerator constructed from a form of exact filtration has weight
`w(f) + ℓ + 1`.  This is the Fourier-expansion formulation of the statement
that `A ∂ Φ + w(f) B Φ` belongs to the weight `w(f) + ℓ + 1` piece. -/
theorem theta_hasWeight_target
    (f : ModularFormMod ℓ k) :
    HasWeight f.Theta (ThetaTargetWeight f) := by
  by_cases hf : f = 0
  · subst f
    unfold HasWeight ModularFormMod.hasWeight
    exact ⟨0, by simp⟩
  · by_cases htheta : f.Theta = 0
    · rw [htheta]
      unfold HasWeight ModularFormMod.hasWeight
      exact ⟨0, by simp⟩
    · /-
  Proof note: follow Proposition 1.44: choose the polynomial representative of
  exact filtration `w(f)`, apply the identity
  `12 θ Φ = A ∂ Φ + w(f) B Φ`, and use that the two summands have weight
  `w(f) + ℓ + 1`.  The project still needs formal definitions of the
  polynomial derivation and the reduced `A`, `B` identity before this can be
  translated into `HasWeight`.
  -/
      /-
      The remaining nonzero case is the integral Ramanujan lift from the
      proof of Proposition 1.44.  The exact missing object is now exposed as
      a `ThetaRamanujanCertificate`; its downstream consequences are proved
      in `PaperSteps`.
      -/
      exact theta_hasWeight_target_of_exact_integral_reduction f
        (paper_exact_theta_lift f)

/-- The numerator above has a lower-weight representative exactly when the
filtration is divisible by `ℓ`.  This is the formal counterpart of the paper's
claim that `A` divides `A ∂ Φ + w(f) B Φ` exactly when `w(f) = 0` in
`𝔽ₚ`. -/
theorem theta_hasLowerWeight_iff_prime_divides
    (f : ModularFormMod ℓ k) :
    HasLowerWeight f.Theta (ThetaTargetWeight f) ↔
      PrimeDividesFiltration f := by
  by_cases hf : f = 0
  · subst f
    constructor
    · intro _
      simp [PrimeDividesFiltration]
    · intro _
      refine ⟨0, ?_, ?_⟩
      · simp [ThetaTargetWeight]
      · unfold HasWeight ModularFormMod.hasWeight
        exact ⟨0, by simp⟩
  /-
  The remaining nonzero case is the Hasse-divisibility/drop argument in the
  proof of Proposition 1.44.  The exact missing object is now exposed as a
  `ThetaDropCertificate`; its conversion to divisibility is proved in
  `PaperSteps`.
  -/
  exact theta_hasLowerWeight_iff_prime_divides_of_drop_criterion f
    (paper_hasse_kernel_and_theta_drop f).2

/-! ## Proposition 1.44 -/

/-- Proposition 1.44(2), inequality form. -/
theorem Filt_Theta_bound
    (f : ModularFormMod ℓ k) :
    f.Theta.Filtration ≤ f.Filtration + (ℓ + 1) := by
  by_cases htheta : f.Theta = 0
  · rw [htheta, ModularFormMod.Filtration_zero]
    by_cases hf : f = 0
    · simp [hf] <;> omega
    · letI : NeZero f := ⟨hf⟩
      have hnonneg := filtration_nonneg f
      omega
  · letI : NeZero f.Theta := ⟨htheta⟩
    simpa [ThetaTargetWeight] using
      (ModularFormMod.Filtration_le (theta_hasWeight_target f))

/-- Proposition 1.44(2), equality characterization. -/
theorem Filt_Theta_iff
    (f : ModularFormMod ℓ k) :
    f.Theta.Filtration = f.Filtration + (ℓ + 1) ↔
      ¬PrimeDividesFiltration f := by
  by_cases htheta : f.Theta = 0
  · by_cases hf : f = 0
    · subst f
      simp [ThetaTargetWeight, PrimeDividesFiltration] <;> omega
    · letI : NeZero f := ⟨hf⟩
      have hnonneg := filtration_nonneg f
      have htarget : 0 < ThetaTargetWeight f := by
        dsimp [ThetaTargetWeight]
        omega
      have hlower : HasLowerWeight f.Theta (ThetaTargetWeight f) := by
        refine ⟨0, htarget, ?_⟩
        rw [htheta]
        exact ⟨0, by simp⟩
      have hdiv := (theta_hasLowerWeight_iff_prime_divides f).1 hlower
      constructor
      · intro heq
        rw [htheta, ModularFormMod.Filtration_zero] at heq
        omega
      · intro hndiv
        exact (hndiv hdiv).elim
  · letI : NeZero f.Theta := ⟨htheta⟩
    constructor
    · intro heq hdiv
      have hlower := (theta_hasLowerWeight_iff_prime_divides f).2 hdiv
      have hlt :=
        (lowerWeight_iff_filtration_lt f.Theta (ThetaTargetWeight f)).1 hlower
      rw [heq] at hlt
      exact (lt_irrefl _ hlt)
    · intro hndiv
      apply le_antisymm (Filt_Theta_bound f)
      by_contra hnot
      have hlt : f.Theta.Filtration < ThetaTargetWeight f :=
        lt_of_not_ge hnot
      have hlower :=
        (lowerWeight_iff_filtration_lt f.Theta (ThetaTargetWeight f)).2 hlt
      exact hndiv ((theta_hasLowerWeight_iff_prime_divides f).1 hlower)

end FiltrationTheta
