import PartitionsLeanblueprint.RamanujanCongruence.IntegerModularForm.Defs
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Ideal.NatInt
import Mathlib.RingTheory.Int.Basic

/-!
# Modular forms with p-integral Fourier coefficients

`PIntegralModularForm p k` consists of a level-one modular form of weight `k` whose
Fourier expansion has coefficients in the localization of `ℤ` at the prime ideal `(p)`.
-/

open ModularForm PowerSeries MatrixGroups UpperHalfPlane Finset.Nat Finset

namespace PIntegralModularForm

variable (p : ℕ) [Fact p.Prime]

noncomputable section

/-- The prime ideal of `ℤ` generated by the prime number `p`. -/
def primeIdeal : Ideal ℤ := Ideal.span {(p : ℤ)}

instance primeIdeal_isPrime : (primeIdeal p).IsPrime :=
  Ideal.isPrime_span_singleton_of_prime <|
    Int.prime_iff_natAbs_prime.mpr (by simpa using (Fact.out : Nat.Prime p))

/-- The valuation ring of `ℚ` at the prime ideal `p`. -/
abbrev CoeffRing := Localization.AtPrime (primeIdeal p)

local notation "ℤ(" p:max ")"  => CoeffRing p


/-- The canonical embedding of the p-local integers into `ℂ`, obtained by first mapping into `ℚ`.
-/
noncomputable def toComplex : CoeffRing p →+* ℂ :=
  (Rat.castHom ℂ).comp (IsLocalization.map (M := (primeIdeal p).primeCompl)
    (T := nonZeroDivisors ℚ) (S := Localization.AtPrime (primeIdeal p)) (Q := ℚ)
    (Int.castRingHom ℚ) (by
      intro x hx
      apply mem_nonZeroDivisors_iff_ne_zero.mpr
      intro hzero
      apply hx
      have hxzero : (x : ℤ) = 0 := by
        change (x : ℚ) = 0 at hzero
        exact_mod_cast hzero
      simpa [hxzero] using (primeIdeal p).zero_mem))

/-- The map from p-local integers into `ℚ` is injective. -/
theorem toRat_injective : Function.Injective
    (IsLocalization.map (M := (primeIdeal p).primeCompl) (T := nonZeroDivisors ℚ)
      (S := Localization.AtPrime (primeIdeal p)) (Q := ℚ) (Int.castRingHom ℚ) (by
        intro x hx
        apply mem_nonZeroDivisors_iff_ne_zero.mpr
        intro hzero
        apply hx
        have hxzero : (x : ℤ) = 0 := by
          change (x : ℚ) = 0 at hzero
          exact_mod_cast hzero
        simpa [hxzero] using (primeIdeal p).zero_mem)) := by
  exact IsLocalization.map_injective_of_injective' (M := (primeIdeal p).primeCompl)
    (Rₘ := Localization.AtPrime (primeIdeal p)) (Sₘ := ℚ)
    (hf := by
      intro x hx
      apply mem_nonZeroDivisors_iff_ne_zero.mpr
      intro hzero
      apply hx
      have hxzero : (x : ℤ) = 0 := by
        change (x : ℚ) = 0 at hzero
        exact_mod_cast hzero
      simpa [hxzero] using (primeIdeal p).zero_mem)
    (hN := by simp)
    (hf' := Int.cast_injective)

theorem toComplex_injective : Function.Injective (toComplex p) := by
  intro x y h
  apply (toRat_injective p)
  exact (Rat.castHom ℂ).injective h

end

end PIntegralModularForm

/-- A level-one modular form whose Fourier coefficients lie in `ℤ_(p)`. -/
structure PIntegralModularForm (p : ℕ) [Fact p.Prime] (k : ℤ) where
  fourier : PowerSeries (PIntegralModularForm.CoeffRing p)
  carrier : ModularForm 𝒮ℒ k
  carrier_eq : qExpansion 1 carrier = map (PIntegralModularForm.toComplex p) fourier

namespace PIntegralModularForm

variable {p : ℕ} [hp : Fact (Nat.Prime p)] {k : ℤ}

noncomputable section

/-- The `n`th Fourier coefficient. -/
def coeff (n : ℕ) (f : PIntegralModularForm p k) : CoeffRing p := f.fourier.coeff n

instance : Zero (PIntegralModularForm p k) where
  zero := ⟨0, 0, by
    change qExpansion 1 (0 : ℍ → ℂ) = map (toComplex p) (0 : PowerSeries (CoeffRing p))
    rw [UpperHalfPlane.qExpansion_zero, map_zero]⟩

instance : Inhabited (PIntegralModularForm p k) := ⟨0⟩

instance : FunLike (PIntegralModularForm p k) ℍ ℂ where
  coe f := f.carrier
  coe_injective f g h := by
    cases f with
    | mk ff fc hfc =>
      cases g with
      | mk gf gc hgc =>
        have hfunc : (fc : ℍ → ℂ) = gc := by simpa using h
        have hcar : fc = gc := by
          exact DFunLike.coe_injective hfunc
        have hq : map (toComplex p) ff = map (toComplex p) gf := by
          calc
            map (toComplex p) ff = qExpansion 1 fc := hfc.symm
            _ = qExpansion 1 gc := congrArg
              (fun c : ModularForm 𝒮ℒ k => qExpansion 1 c) hcar
            _ = map (toComplex p) gf := hgc
        have hfg : ff = gf := by
          apply PowerSeries.map_injective (toComplex p) (toComplex_injective p)
          exact hq
        subst gf
        subst gc
        rfl

@[simp]
theorem coe_def (f : PIntegralModularForm p k) : f.carrier = (f : ℍ → ℂ) := rfl

@[ext]
theorem ext {f g : PIntegralModularForm p k}
    (h : ∀ n, f.coeff n = g.coeff n) : f = g := by
  cases f with
  | mk ff fc hfc =>
    cases g with
    | mk gf gc hgc =>
      have hfourier : ff = gf := by
        apply PowerSeries.ext
        exact h
      subst gf
      have hcarrier : fc = gc := ModularForm.qExpansion_injective zero_lt_one (by simp)
        (hfc.trans hgc.symm)
      subst gc
      rfl

theorem ext₂ {f g : PIntegralModularForm p k} (h : ∀ z, f z = g z) : f = g :=
  DFunLike.ext f g h

instance : Add (PIntegralModularForm p k) where
  add f g := ⟨f.fourier + g.fourier, f.carrier + g.carrier, by
    calc
      qExpansion 1 (f.carrier + g.carrier) =
          qExpansion 1 f.carrier + qExpansion 1 g.carrier :=
        ModularForm.qExpansion_add zero_lt_one (by simp) _ _
      _ = map (toComplex p) (f.fourier + g.fourier) := by
        rw [f.carrier_eq, g.carrier_eq, map_add]⟩

instance : Neg (PIntegralModularForm p k) where
  neg f := ⟨-f.fourier, -f.carrier, by
    calc
      qExpansion 1 (-f.carrier) = -qExpansion 1 f.carrier :=
        ModularForm.qExpansion_neg zero_lt_one (by simp) _
      _ = map (toComplex p) (-f.fourier) := by rw [f.carrier_eq, map_neg]⟩

instance : Sub (PIntegralModularForm p k) := ⟨fun f g => f + -g⟩

noncomputable instance : Algebra (CoeffRing p) ℂ := (toComplex p).toAlgebra

instance : SMul (CoeffRing p) (PIntegralModularForm p k) where
  smul a f := ⟨a • f.fourier, (toComplex p a) • f.carrier, by
    calc
      qExpansion 1 ((toComplex p a) • f.carrier) =
          (toComplex p a) • qExpansion 1 f.carrier :=
        ModularForm.qExpansion_smul zero_lt_one (by simp) _ _
      _ = map (toComplex p) (a • f.fourier) := by
        rw [f.carrier_eq]
        apply PowerSeries.ext
        intro n
        simp [PowerSeries.coeff_map]⟩

instance : SMul ℕ (PIntegralModularForm p k) :=
  ⟨fun n f => (n : CoeffRing p) • f⟩

instance : SMul ℤ (PIntegralModularForm p k) :=
  ⟨fun z f => (z : CoeffRing p) • f⟩

/-- Multiplication of p-integral modular forms, with the expected sum of weights. -/
protected def mul {k j : ℤ} (f : PIntegralModularForm p k) (g : PIntegralModularForm p j) :
    PIntegralModularForm p (k + j) where
  fourier := f.fourier * g.fourier
  carrier := f.carrier.mul g.carrier
  carrier_eq := calc
    qExpansion 1 (f.carrier.mul g.carrier) = (f.carrier.mul g.carrier).qexp :=
      (ModularForm.qexp_eq' _).symm
    _ = f.carrier.qexp * g.carrier.qexp := ModularForm.qexp_mul _ _
    _ = map (toComplex p) (f.fourier * g.fourier) := by
      rw [ModularForm.qexp_eq' f.carrier, f.carrier_eq,
        ModularForm.qexp_eq' g.carrier, g.carrier_eq, map_mul]

/-- Natural powers of a p-integral modular form. -/
protected def pow {k : ℤ} (f : PIntegralModularForm p k) (n : ℕ) :
    PIntegralModularForm p (n * k) where
  fourier := f.fourier ^ n
  carrier := f.carrier.pow n
  carrier_eq := calc
    qExpansion 1 (f.carrier.pow n) = (f.carrier.pow n).qexp :=
      (ModularForm.qexp_eq' _).symm
    _ = f.carrier.qexp ^ n := ModularForm.qexp_pow _ _
    _ = map (toComplex p) (f.fourier ^ n) := by
      rw [ModularForm.qexp_eq' f.carrier, f.carrier_eq, map_pow]

/-- The constant p-integral modular form of weight zero. -/
@[simp]
theorem coeff_def (f : PIntegralModularForm p k) (n : ℕ) :
    f.fourier.coeff n = f.coeff n := rfl

@[simp]
theorem fourier_add (f g : PIntegralModularForm p k) : (f + g).fourier = f.fourier + g.fourier := rfl

@[simp]
theorem coeff_add (f g : PIntegralModularForm p k) (n : ℕ) :
    (f + g).coeff n = f.coeff n + g.coeff n := rfl

@[simp]
theorem fourier_zero : (0 : PIntegralModularForm p k).fourier = 0 := rfl

@[simp]
theorem coeff_zero (n : ℕ) : (0 : PIntegralModularForm p k).coeff n = 0 := rfl

@[simp]
theorem fourier_neg (f : PIntegralModularForm p k) : (-f).fourier = -f.fourier := rfl

@[simp]
theorem coeff_neg (f : PIntegralModularForm p k) (n : ℕ) :
    (-f).coeff n = -f.coeff n := rfl

@[simp]
theorem fourier_mul {k j : ℤ} (f : PIntegralModularForm p k) (g : PIntegralModularForm p j) :
    (f.mul g).fourier = f.fourier * g.fourier := rfl

@[simp]
theorem coeff_mul {k j : ℤ} (f : PIntegralModularForm p k) (g : PIntegralModularForm p j)
    (n : ℕ) : (f.mul g).coeff n = ∑ x ∈ antidiagonal n, f.coeff x.1 * g.coeff x.2 := by
  simp only [coeff, fourier_mul, PowerSeries.coeff_mul]

@[simp]
theorem fourier_pow (f : PIntegralModularForm p k) (n : ℕ) :
    (f.pow n).fourier = f.fourier ^ n := rfl

@[simp]
theorem coeff_pow (f : PIntegralModularForm p k) (n m : ℕ) :
    (f.pow n).coeff m = ∑ x ∈ finsuppAntidiag (range n) m, ∏ i ∈ range n, f.coeff (x i) := by
  simp only [coeff, fourier_pow, PowerSeries.coeff_pow]

@[simp]
theorem coe_add (f g : PIntegralModularForm p k) : ⇑(f + g) = (f : ℍ → ℂ) + g := rfl

@[simp]
theorem coe_neg (f : PIntegralModularForm p k) : ⇑(-f) = -(f : ℍ → ℂ) := rfl

@[simp]
theorem coe_sub (f g : PIntegralModularForm p k) : ⇑(f - g) = (f : ℍ → ℂ) - g := rfl

@[simp]
theorem coe_smuln (f : PIntegralModularForm p k) (n : ℕ) :
    ⇑(n • f) = n • (f : ℍ → ℂ) := by
  change (toComplex p (n : CoeffRing p)) • (f : ℍ → ℂ) = _
  rw [map_natCast]
  exact Nat.cast_smul_eq_nsmul ℂ n (f : ℍ → ℂ)

@[simp]
theorem coe_smulz (f : PIntegralModularForm p k) (z : ℤ) :
    ⇑(z • f) = z • (f : ℍ → ℂ) := by
  change (toComplex p (z : CoeffRing p)) • (f : ℍ → ℂ) = _
  rw [map_intCast]
  exact Int.cast_smul_eq_zsmul ℂ z (f : ℍ → ℂ)

instance : AddCommGroup (PIntegralModularForm p k) :=
  DFunLike.coe_injective.addCommGroup _ rfl coe_add coe_neg coe_sub coe_smuln coe_smulz

def coeAddHom : PIntegralModularForm p k →+ (ℍ → ℂ) where
  toFun f := DFunLike.coe f
  map_zero' := rfl
  map_add' _ _ := rfl

instance : Module (CoeffRing p) (PIntegralModularForm p k) :=
  Function.Injective.module (CoeffRing p) coeAddHom DFunLike.coe_injective fun _ _ => rfl

end
end PIntegralModularForm
