import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.CoprimeAbarBbar
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.MAlgebra
import PartitionsLeanblueprint.RamanujanCongruence.AiAssisted.SwD.AbarSubOne
import Mathlib.RingTheory.Jacobson.Ring
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.KrullDimension.Field

namespace PIntegralModularForm.SwD

open DirectSum

noncomputable section

variable {p : ℕ} [isLargePrime p]

/-- Polynomials homogeneous in weighted degree modulo `p-1`, where `X` has
weight `4` and `Y` has weight `6`. -/
structure ResidueWeightedPolynomial (k : ZMod (p - 1)) where
  polynomial : ResiduePolynomial p
  homogeneous : ∀ m ∈ polynomial.support,
    (PIntegralModularForm.weightedDegree m : ZMod (p - 1)) = k

/-- The principal ideal generated by the Hasse relation `Ã - 1`. -/
def hasseIdeal : Ideal (ResiduePolynomial p) :=
  Ideal.span {Abar (p := p) - 1}

variable {k : ZMod (p - 1)}

/-- Every form of a fixed weight is represented by a weighted-homogeneous
polynomial in the reductions of `E₄` and `E₆`. -/
theorem exists_weighted_representation (f : ModularFormMod p k) :
  ∃ P : ResidueWeightedPolynomial (p := p) k,
    evaluateResiduePolynomial (p := p) P.polynomial = f.fourier := by
  obtain ⟨j, hj, g, hg⟩ := f.Exists_reduce
  let fLift : PIntegralModularForm p j :=
    PIntegralModularForm.ofInteger (p := p) g
  let Pmod : ResiduePolynomial p :=
    reducePolynomial (p := p)
      (PIntegralModularForm.polynomial (p := p) fLift)
  have hEval : evaluateResiduePolynomial (p := p) Pmod = f.fourier := by
    calc
      evaluateResiduePolynomial (p := p) Pmod =
          PowerSeries.map (PIntegralModularForm.coeffToZMod (p := p))
            (PIntegralModularForm.evaluateE4E6 (p := p)
              (PIntegralModularForm.polynomial (p := p) fLift)) := by
            exact evaluateResiduePolynomial_reducePolynomial (p := p)
              (PIntegralModularForm.polynomial (p := p) fLift)
      _ = PowerSeries.map (PIntegralModularForm.coeffToZMod (p := p)) fLift.fourier := by
        rw [PIntegralModularForm.evaluate_polynomial]
      _ = (fLift.Reduce).fourier := rfl
      _ = (g.Reduce p).fourier := by
        exact congrArg ModularFormMod.fourier
          (PIntegralModularForm.Reduce_ofInteger (p := p) g)
      _ = f.fourier := by
        rw [IntegerModularForm.fourier_Reduce, hg]
  refine ⟨⟨Pmod, ?_⟩, hEval⟩
  intro m hm
  have hmLift : m ∈
      (PIntegralModularForm.polynomial (p := p) fLift).support :=
    MvPolynomial.support_map_subset
      (f := PIntegralModularForm.coeffToZMod (p := p))
      (PIntegralModularForm.polynomial (p := p) fLift) hm
  have hdegree := PIntegralModularForm.polynomial_isHomogeneous
    (p := p) fLift hmLift
  exact (congrArg (fun n : ℤ => (n : ZMod (p - 1))) hdegree).trans hj



/-- Embed scalars as constant forms in the zeroth graded component. -/
def scalarIntoGradedForms : ZMod p →+*
    DirectSum (ZMod (p - 1)) (fun k => ModularFormMod p k) where
  toFun c := DirectSum.of _ 0 (ModularFormMod.const c)
  map_zero' := by
    have h : ModularFormMod.const (0 : ZMod p) = 0 := by
      apply ModularFormMod.fourier_inj
      simp
    rw [h]
    exact map_zero (DirectSum.of (fun k : ZMod (p - 1) => ModularFormMod p k) 0)
  map_one' := by
    have h : ModularFormMod.const (1 : ZMod p) = 1 := by
      rw [ModularFormMod.one_def]
    rw [h, DirectSum.of_zero_one]
  map_add' c d := by
    have h : ModularFormMod.const (c + d) =
        ModularFormMod.const c + ModularFormMod.const d := by
      apply ModularFormMod.fourier_inj
      simp
    simpa using congrArg
      (DirectSum.of (fun k : ZMod (p - 1) => ModularFormMod p k) 0) h
  map_mul' c d := by
    calc
      DirectSum.of _ 0 (ModularFormMod.const (c * d)) =
          DirectSum.of _ (0 + 0)
            ((ModularFormMod.const c).mul (ModularFormMod.const d)) := by
        apply DirectSum.of_eq_of_gradedMonoid_eq
        apply ModularFormMod.gradedMonoid_eq_of_cast (by
          exact (zero_add (0 : ZMod (p - 1))).symm)
        dsimp only [GradedMonoid.mk]
        apply ModularFormMod.fourier_inj
        rw [ModularFormMod.fourier_Mcast, ModularFormMod.fourier_const,
          ModularFormMod.fourier_mul, ModularFormMod.fourier_const]
        exact map_mul (PowerSeries.C (R := ZMod p)) c d
      _ = DirectSum.of _ 0 (ModularFormMod.const c) *
          DirectSum.of _ 0 (ModularFormMod.const d) := by
        symm
        exact DirectSum.of_mul_of (ModularFormMod.const c) (ModularFormMod.const d)

/-- The reductions of the two Eisenstein series, placed in their weight
components of the graded ring. -/
def reducedE4InGradedForms :
    ModularFormMod p (4 : ZMod (p - 1)) :=
  ((PIntegralModularForm.Eis (p := p) 4).Reduce).Mcast (by norm_num)

def reducedE6InGradedForms :
    ModularFormMod p (6 : ZMod (p - 1)) :=
  ((PIntegralModularForm.Eis (p := p) 6).Reduce).Mcast (by norm_num)

/-- Evaluate `Fp[X,Y]` at the reduced `E₄` and `E₆` in the graded ring of
mod-`p` modular forms. This is the surjective homomorphism in Theorem 1.41. -/
def polynomialToGradedForms : ResiduePolynomial p →+*
    DirectSum (ZMod (p - 1)) (fun k => ModularFormMod p k) :=
  MvPolynomial.eval₂Hom (scalarIntoGradedForms (p := p)) (fun i =>
    if i = 0 then
      DirectSum.of _ (4 : ZMod (p - 1)) (reducedE4InGradedForms (p := p))
    else
      DirectSum.of _ (6 : ZMod (p - 1)) (reducedE6InGradedForms (p := p)))

private def weightedDegreeMod (m : Fin 2 →₀ ℕ) : ZMod (p - 1) :=
  (PIntegralModularForm.weightedDegree m : ZMod (p - 1))

private def gradedPower {j : ZMod (p - 1)} (f : ModularFormMod p j) (n : ℕ) :
    ModularFormMod p (n • j) :=
  GradedMonoid.GMonoid.gnpow n f

private def evaluatedMonomialForm (m : Fin 2 →₀ ℕ) (a : ZMod p) :
    ModularFormMod p (weightedDegreeMod (p := p) m) :=
  ((ModularFormMod.const a).mul
      ((gradedPower (p := p) (reducedE4InGradedForms (p := p)) (m 0)).mul
        (gradedPower (p := p) (reducedE6InGradedForms (p := p)) (m 1)))).Mcast (by
          simp [weightedDegreeMod, PIntegralModularForm.weightedDegree]
          ring)

private theorem polynomialToGradedForms_monomial (m : Fin 2 →₀ ℕ) (a : ZMod p) :
    polynomialToGradedForms (p := p) (MvPolynomial.monomial m a) =
      DirectSum.of _ (weightedDegreeMod (p := p) m)
        (evaluatedMonomialForm (p := p) m a) := by
  classical
  rw [polynomialToGradedForms, MvPolynomial.eval₂Hom_monomial]
  rw [Finsupp.prod_fintype m
    (fun i n =>
      (if i = 0 then DirectSum.of _ (4 : ZMod (p - 1))
        (reducedE4InGradedForms (p := p)) else
       DirectSum.of _ (6 : ZMod (p - 1))
        (reducedE6InGradedForms (p := p))) ^ n)
    (by intro i; simp)]
  simp [Fin.prod_univ_succ]
  change DirectSum.of _ 0 (ModularFormMod.const a) *
      (DirectSum.of _ (4 : ZMod (p - 1)) (reducedE4InGradedForms (p := p)) ^ m 0 *
        DirectSum.of _ (6 : ZMod (p - 1)) (reducedE6InGradedForms (p := p)) ^ m 1) = _
  calc
      _ = DirectSum.of _ (0 + ((m 0) • (4 : ZMod (p - 1)) +
          (m 1) • (6 : ZMod (p - 1))))
          ((ModularFormMod.const a).mul
          ((gradedPower (p := p) (reducedE4InGradedForms (p := p)) (m 0)).mul
              (gradedPower (p := p) (reducedE6InGradedForms (p := p)) (m 1)))) := by
        rw [DirectSum.ofPow, DirectSum.ofPow,
          DirectSum.of_mul_of, DirectSum.of_mul_of]
        rfl
    _ = DirectSum.of _ (weightedDegreeMod (p := p) m)
        (evaluatedMonomialForm (p := p) m a) := by
        apply DirectSum.of_eq_of_gradedMonoid_eq
        have hidx : 0 + ((m 0) • (4 : ZMod (p - 1)) +
            (m 1) • (6 : ZMod (p - 1))) = weightedDegreeMod (p := p) m := by
          simp [weightedDegreeMod, PIntegralModularForm.weightedDegree]
          ring
        apply ModularFormMod.gradedMonoid_eq_of_cast hidx
        dsimp only [GradedMonoid.mk, evaluatedMonomialForm]

private def weightedPolynomialEvalForm (P : ResidueWeightedPolynomial (p := p) k) :
    ModularFormMod p k :=
  ∑ m ∈ P.polynomial.support,
    if h : weightedDegreeMod (p := p) m = k then
      (evaluatedMonomialForm (p := p) m (P.polynomial.coeff m)).Mcast h
    else 0

private def modularFormFourierHom (j : ZMod (p - 1)) :
    ModularFormMod p j →+ PowerSeries (ZMod p) where
  toFun := ModularFormMod.fourier
  map_zero' := rfl
  map_add' _ _ := rfl

private theorem gradedPower_fourier {j : ZMod (p - 1)}
    (f : ModularFormMod p j) (n : ℕ) :
    (gradedPower (p := p) f n).fourier = f.fourier ^ n := by
  induction n with
  | zero =>
      have h := GradedMonoid.GMonoid.gnpow_zero' (GradedMonoid.mk j f)
      have h' := congrArg
        (fun x : GradedMonoid (ModularFormMod p) => x.snd.fourier) h
      have hone : (1 : GradedMonoid (ModularFormMod p)).snd.fourier = 1 := by
        simp [GradedMonoid.GOne.one, ModularFormMod.one_def]
      rw [hone] at h'
      simpa [gradedPower, GradedMonoid.mk, ModularFormMod.one_def] using h'
  | succ n ih =>
      have h := GradedMonoid.GMonoid.gnpow_succ' n (GradedMonoid.mk j f)
      have h' : (gradedPower (p := p) f n.succ).fourier =
          (GradedMonoid.mk (n • j) (GradedMonoid.GMonoid.gnpow n f) *
            GradedMonoid.mk j f).snd.fourier := by
        simpa [gradedPower, GradedMonoid.mk] using congrArg
          (fun x : GradedMonoid (ModularFormMod p) => x.snd.fourier) h
      calc
        (gradedPower (p := p) f n.succ).fourier =
            (GradedMonoid.mk (n • j) (GradedMonoid.GMonoid.gnpow n f) *
              GradedMonoid.mk j f).snd.fourier := h'
        _ = f.fourier ^ n * f.fourier := by
          change (ModularFormMod.mul (gradedPower (p := p) f n) f).fourier = _
          rw [ModularFormMod.fourier_mul, ih]
        _ = f.fourier ^ n.succ := by rw [pow_succ]

private theorem polynomialToGradedForms_weighted
    (P : ResidueWeightedPolynomial (p := p) k) :
    polynomialToGradedForms (p := p) P.polynomial =
      DirectSum.of _ k (weightedPolynomialEvalForm (p := p) P) := by
  classical
  have hpolySum := P.polynomial.as_sum
  have hmap := map_sum (polynomialToGradedForms (p := p))
    (fun m : Fin 2 →₀ ℕ => MvPolynomial.monomial m (P.polynomial.coeff m))
    P.polynomial.support
  have hformSum := map_sum (DirectSum.of (fun j : ZMod (p - 1) => ModularFormMod p j) k)
    (fun m : Fin 2 →₀ ℕ =>
      if h : weightedDegreeMod (p := p) m = k then
        (evaluatedMonomialForm (p := p) m (P.polynomial.coeff m)).Mcast h
      else 0) P.polynomial.support
  rw [hpolySum, hmap, weightedPolynomialEvalForm, hformSum]
  apply Finset.sum_congr rfl
  intro m hm
  rw [polynomialToGradedForms_monomial]
  have hdegree : weightedDegreeMod (p := p) m = k := P.homogeneous m hm
  rw [dite_eq_left hdegree]
  apply DirectSum.of_eq_of_gradedMonoid_eq
  apply ModularFormMod.gradedMonoid_eq_of_cast hdegree
  rfl

private theorem evaluatedMonomialForm_fourier (m : Fin 2 →₀ ℕ) (a : ZMod p) :
    (evaluatedMonomialForm (p := p) m a).fourier =
      evaluateResiduePolynomial (p := p) (MvPolynomial.monomial m a) := by
  classical
  have hE4 : (reducedE4InGradedForms (p := p)).fourier =
      PowerSeries.map (PIntegralModularForm.coeffToZMod (p := p))
        (PIntegralModularForm.Eis (p := p) 4).fourier := by
    simp [reducedE4InGradedForms, PIntegralModularForm.fourier_Reduce]
  have hE6 : (reducedE6InGradedForms (p := p)).fourier =
      PowerSeries.map (PIntegralModularForm.coeffToZMod (p := p))
        (PIntegralModularForm.Eis (p := p) 6).fourier := by
    simp [reducedE6InGradedForms, PIntegralModularForm.fourier_Reduce]
  simp only [evaluatedMonomialForm, ModularFormMod.fourier_Mcast,
    ModularFormMod.const_mul, ModularFormMod.fourier_Mcast,
    ModularFormMod.fourier_mul, ModularFormMod.fourier_smul]
  rw [gradedPower_fourier, gradedPower_fourier,
    PowerSeries.smul_eq_C_mul, hE4, hE6]
  simp [evaluateResiduePolynomial, MvPolynomial.eval₂Hom_monomial,
    Finsupp.prod_fintype, Fin.prod_univ_succ]

private theorem weightedPolynomialEvalForm_fourier
    (P : ResidueWeightedPolynomial (p := p) k) :
    (weightedPolynomialEvalForm (p := p) P).fourier =
      evaluateResiduePolynomial (p := p) P.polynomial := by
  classical
  have hpolySum := P.polynomial.as_sum
  have hevalSum := map_sum (evaluateResiduePolynomial (p := p))
    (fun m : Fin 2 →₀ ℕ => MvPolynomial.monomial m (P.polynomial.coeff m))
    P.polynomial.support
  have hformSum := map_sum (modularFormFourierHom (p := p) k)
    (fun m : Fin 2 →₀ ℕ =>
      if h : weightedDegreeMod (p := p) m = k then
        (evaluatedMonomialForm (p := p) m (P.polynomial.coeff m)).Mcast h
      else 0) P.polynomial.support
  rw [hpolySum, hevalSum, weightedPolynomialEvalForm]
  change modularFormFourierHom (p := p) k
    (∑ m ∈ P.polynomial.support,
      if h : weightedDegreeMod (p := p) m = k then
        (evaluatedMonomialForm (p := p) m (P.polynomial.coeff m)).Mcast h
      else 0) = _
  rw [hformSum]
  apply Finset.sum_congr rfl
  intro m hm
  have hdegree : weightedDegreeMod (p := p) m = k := P.homogeneous m hm
  simp [hdegree, modularFormFourierHom, evaluatedMonomialForm_fourier]

/-- The graded image of a weighted polynomial is concentrated in its weight
component, with the expected Fourier expansion. -/
theorem polynomialToGradedForms_weighted_fourier
    (P : ResidueWeightedPolynomial (p := p) k) :
    ∃ g : ModularFormMod p k,
      polynomialToGradedForms (p := p) P.polynomial = DirectSum.of _ k g ∧
        g.fourier = evaluateResiduePolynomial (p := p) P.polynomial := by
  exact ⟨weightedPolynomialEvalForm (p := p) P,
    polynomialToGradedForms_weighted (p := p) P,
    weightedPolynomialEvalForm_fourier (p := p) P⟩

/-- The evaluation homomorphism is surjective, by the weighted polynomial
representations of mod-`p` modular forms. -/
theorem polynomialToGradedForms_surjective :
    Function.Surjective (polynomialToGradedForms (p := p)) := by
  intro x
  induction x using DirectSum.induction_on with
  | zero =>
      exact ⟨0, by simp [polynomialToGradedForms]⟩
  | of k f =>
      obtain ⟨P, hP⟩ := exists_weighted_representation (p := p) f
      refine ⟨P.polynomial, ?_⟩
      rw [polynomialToGradedForms_weighted]
      apply congrArg (DirectSum.of _ k)
      apply ModularFormMod.fourier_inj
      rw [weightedPolynomialEvalForm_fourier, hP]
  | add x y hx hy =>
      obtain ⟨P, hP⟩ := hx
      obtain ⟨Q, hQ⟩ := hy
      exact ⟨P + Q, by rw [map_add, hP, hQ]⟩


local notation "Ker " p:max => RingHom.ker (Malgebra.evaluate (p := p))

theorem hasseIdeal_le_Ker : hasseIdeal ≤ Ker p := by
  refine Ideal.span_le.2 fun x hx => ?_
  obtain rfl := Set.mem_singleton_iff.mp hx
  apply Subtype.ext
  change evaluateResiduePolynomial (Abar - 1) = 0
  rw [map_sub, evaluate_Abar, map_one, sub_self]



theorem prime_Ker : Ideal.IsPrime (Ker p) := RingHom.ker_isPrime _


theorem not_maximal_Ker : ¬ Ideal.IsMaximal (Ker p) := by
  intro hmax
  let : Field (ResiduePolynomial p ⧸ Ker p) :=
    Ideal.Quotient.field (Ker p)
  have : Module.Finite (ZMod p) (ResiduePolynomial p ⧸ Ker p) :=
    finite_of_finite_type_of_isJacobsonRing (ZMod p) _
  have : Finite (Malgebra p) :=
    Finite.of_equiv (h := Module.finite_of_finite (ZMod p)) _
      (Malgebra.evaluate.quotientKerEquivOfSurjective
        Malgebra.evaluate_surjective).toEquiv
  exact not_finite (Malgebra p)

theorem isPrime_hasseIdeal : Ideal.IsPrime (hasseIdeal (p := p)) :=
  Ideal.isPrime_span_singleton_of_prime Prime_Abar_sub_one


/-- The kernel of Fourier evaluation is generated by the Hasse relation. -/
theorem Ker_eq_hasseIdeal : Ker p = hasseIdeal := by
  have hgen : Abar (p := p) - MvPolynomial.C (1 : ZMod p) ≠ 0 := by
    exact Prime_Abar_sub_one.ne_zero
  have hbot : (⊥ : Ideal (ResiduePolynomial p)) < hasseIdeal := by
    rw [bot_lt_iff_ne_bot]
    simpa [hasseIdeal] using hgen
  let : (⊥ : Ideal (ResiduePolynomial p)).IsPrime := inferInstance
  let : (hasseIdeal (p := p)).IsPrime := isPrime_hasseIdeal
  let : (Ker p).IsPrime := prime_Ker
  by_contra hne
  have hlt : hasseIdeal < Ker p :=
    lt_of_le_of_ne hasseIdeal_le_Ker (Ne.symm hne)
  obtain ⟨M, hM, hKM⟩ := Ideal.exists_le_maximal (Ker p) prime_Ker.ne_top
  let : M.IsMaximal := hM
  have hKMlt : Ker p < M := lt_of_le_of_ne hKM (by
    intro heq
    exact not_maximal_Ker (heq ▸ hM))
  have hheight0 : 1 ≤ (hasseIdeal (p := p)).height := by
    simpa using Ideal.height_add_one_le_of_lt_of_isPrime hbot
  have hheight1 : (hasseIdeal (p := p)).height + 1 ≤ (Ker p).height :=
    Ideal.height_add_one_le_of_lt_of_isPrime hlt
  have hheight2 : (Ker p).height + 1 ≤ M.height :=
    Ideal.height_add_one_le_of_lt_of_isPrime hKMlt
  have hheight3 : (3 : ℕ∞) ≤ M.height := by
    calc
      3 = (1 : ℕ∞) + 1 + 1 := by norm_num
      _ ≤ ((hasseIdeal (p := p)).height + 1) + 1 := by gcongr
      _ ≤ (Ker p).height + 1 := by gcongr
      _ ≤ M.height := hheight2
  have hdim : ringKrullDim (ResiduePolynomial p) ≤ 2 := by
    rw [MvPolynomial.ringKrullDim_of_isNoetherianRing_of_finite]
    simp
  have hMdim : M.height ≤ ringKrullDim (ResiduePolynomial p) :=
    Ideal.height_le_ringKrullDim_of_ne_top Ideal.IsPrime.ne_top'
  have hheight3' : (3 : WithBot ℕ∞) ≤ (M.height : WithBot ℕ∞) :=
    WithBot.coe_le_coe.mpr hheight3
  have : (3 : WithBot ℕ∞) ≤ 2 := hheight3'.trans (hMdim.trans hdim)
  norm_num at this



/-- Theorem 1.41: the quotient by the Hasse relation is
the graded ring of mod-`p` modular forms. -/
noncomputable def Malgebra.ringEquiv :
    Malgebra p ≃+* ResiduePolynomial p ⧸ hasseIdeal :=
  (Malgebra.evaluate.quotientKerEquivOfSurjective
    Malgebra.evaluate_surjective).symm.trans
      (Ideal.quotEquivOfEq Ker_eq_hasseIdeal)


private theorem ringEquiv_evaluate (P : ResiduePolynomial p) :
    Malgebra.ringEquiv (p := p) (Malgebra.evaluate (p := p) P) =
      Ideal.Quotient.mk (hasseIdeal (p := p)) P := by
  simp [Malgebra.ringEquiv]


/-- Congruence modulo the Hasse relation preserves evaluation. -/
theorem hasseIdeal_sound (P Q : ResidueWeightedPolynomial (p := p) k)
  (h : P.polynomial - Q.polynomial ∈ hasseIdeal (p := p)) :
    evaluateResiduePolynomial (p := p) P.polynomial =
      evaluateResiduePolynomial (p := p) Q.polynomial := by
  have hquot :
      Ideal.Quotient.mk (hasseIdeal (p := p))
          (P.polynomial - Q.polynomial) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr h
  have hevalzero : Malgebra.evaluate (p := p)
      (P.polynomial - Q.polynomial) = 0 := by
    apply (Malgebra.ringEquiv (p := p)).injective
    rw [ringEquiv_evaluate]
    simpa using hquot
  have hincl := congrArg (Malgebra.inclusion (p := p)) hevalzero
  have hevalzero' :
      evaluateResiduePolynomial (p := p) (P.polynomial - Q.polynomial) = 0 := by
    simpa only [Malgebra.inclusion_evaluate, map_zero] using hincl
  rw [map_sub] at hevalzero'
  exact sub_eq_zero.mp hevalzero'

/-- Equality after evaluation implies congruence modulo the Hasse relation. -/
theorem hasseIdeal_complete (P Q : ResidueWeightedPolynomial (p := p) k)
  (h : evaluateResiduePolynomial (p := p) P.polynomial =
    evaluateResiduePolynomial (p := p) Q.polynomial) :
    P.polynomial - Q.polynomial ∈ hasseIdeal (p := p) := by
  have heval : Malgebra.evaluate (p := p) P.polynomial =
      Malgebra.evaluate (p := p) Q.polynomial := by
    apply Subtype.ext
    exact h
  have hquot :
      Ideal.Quotient.mk (hasseIdeal (p := p)) P.polynomial =
        Ideal.Quotient.mk (hasseIdeal (p := p)) Q.polynomial := by
    have h := congrArg (Malgebra.ringEquiv (p := p)) heval
    rw [ringEquiv_evaluate, ringEquiv_evaluate] at h
    exact h
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  rw [map_sub, sub_eq_zero]
  exact hquot
